### ISSUE TITLE
Question to UIImage -> size

### ISSUE THREAD

**Issue by FrankDoersam** [devxoul/SwiftyImage#12]
Hello,

could you please help me.
I get the following error:
let image1 = UIImage(named: "home")?.si(width: 106, height: 106)

<img width="818" alt="bildschirmfoto 2018-02-21 um 19 04 02" src="https://user-images.githubusercontent.com/16541879/36496903-02de7dd4-173a-11e8-978d-79836deb17ad.png">

Best regards
Frank

**Comment by devxoul** [comment]
What did you expect?

**Comment by cozzin** [comment]
@FrankDoersam Did you expect to draw something on existed image?

**Comment by appsird** [comment]
Frank,

Make certain to place the following import statement in your file:

import SwiftyImage
