### ISSUE TITLE
Problem with applying gradient into resizable UIImage

### ISSUE THREAD

**Issue by NumbRay** [devxoul/SwiftyImage#13]
Here is the snapshot

<img width="651" alt="screen shot 2018-08-20 at 16 52 10" src="https://user-images.githubusercontent.com/3864993/44336503-76824300-a499-11e8-90b6-30afbd06baf1.png">

**Comment by devxoul** [comment]
Theoretically resizable gradient is not supported because SwiftyImage is not a vector :( You may use fixed size for gradient.
