### ISSUE TITLE
UIImage operator overload for addition result is incorrect

### ISSUE THREAD

**Issue by dsowsy** [devxoul/SwiftyImage#5]
The resultant UIImage is upside down and backwards. This can be fixed if you replace: 
```swift
CGContextDrawImage(context, lhsRect, lhs.CGImage)
CGContextDrawImage(context, rhsRect, rhs.CGImage)
```
with this: 
```swift
lhs.drawInRect(lhsRect)
rhs.drawInRect(rhsRect)
```

**Comment by devxoul** [comment]
@dsowsy, Thanks for your report!
Could you please test with #6 PR? If it works properly, I'll merge it and make a new release.
